### ISSUE TITLE
Do something with this.

### ISSUE THREAD

**Issue by chrisjaure** [dhmncivichacks/dhmncivichacks.github.io#1]
We need a user-facing directory of our cool hacks.

**Comment by zo0o0ot** [comment]
Any thoughts?

**Comment by bobwaldron** [comment]
http://dhmncivichacks.blogspot.com/2015/06/civichacks-resourcecentral-v01.html

also, suggested building recycle civic hacks directory in
http://dhmncivichacks.blogspot.com/2015/07/recycle-app-ecosystem-trash-queens-kings.html

**Comment by chrisjaure** [comment]
I used the automatic page generator to start out simple: http://dhmncivichacks.github.io/

We should probably switch to jekyll so we can author in markdown though.

**Comment by mikeputnam** [comment]
I think the scope of this initial issue was handily closed with c5d8a81a0cba95ff788f256f83092670e59b8a55
